#!/usr/bin/env python3
"""Stele config generator (P7-3 §4) — env-scaffolding only.

Emits a ``.env`` template for a Stele mount to stdout:

    python generate_env.py > .env

The post-lift mount is small — two short providers + a handful of env values — so
this is env-scaffolding, not code generation. It emits no code, so it cannot drift
from the package surface. The one piece of real logic is the freshly generated
``STELE_SECRET_KEY``: a valid Fernet key (the same primitive Stele's KEK is built
on — ``cryptography.fernet.Fernet``), so a stranger is never tempted to ship a
placeholder secret.

The field set is the full env floor a real mount needs (it matches what
``examples/reference_app/config.py`` reads and the live ``WebauthnConfig`` /
``EnvKeyEncryptionKeyProvider`` expect).
"""
from __future__ import annotations

from cryptography.fernet import Fernet

TEMPLATE = """\
# Stele mount configuration — generated by examples/generate_env.py.
# Fill the site-specific values, then load it (e.g. `set -a; . ./.env; set +a`).

# The KEK: encrypts session tokens + the TOTP secret at rest. Freshly generated
# below — a real Fernet key. Keep it secret; losing it locks every encrypted value.
STELE_SECRET_KEY={secret_key}

# WebAuthn relying party. STELE_RP_ID is the registrable domain (the page-origin
# host, e.g. localhost). STELE_RP_ORIGIN is the EXACT serving origin (scheme + host
# + port). The browser refuses the ceremony if RP id / origin do not match where
# the page is served — the single most common first-time failure.
STELE_RP_ID=localhost
STELE_RP_NAME=Stele Reference App
STELE_RP_ORIGIN=http://localhost:8000

# The database — a real Postgres (Stele's models use JSONB + bytea; SQLite is not
# viable). Run Stele's baseline migration against it: `alembic upgrade head`.
STELE_DATABASE_URL=postgresql+asyncpg://stele:stele@localhost:5433/stele_ref

# Optional — older KEKs kept decrypt-readable across a key rotation (comma-separated).
# Leave empty unless you are rotating STELE_SECRET_KEY.
#STELE_SECRET_KEYS_PREVIOUS=
"""


def render() -> str:
    return TEMPLATE.format(secret_key=Fernet.generate_key().decode())


if __name__ == "__main__":
    print(render(), end="")
